name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
 Deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Install Hugging Face Hub library
      run: pip install huggingface_hub

    - name: Login to Hugging Face Hub
      uses: huggingface/login@v0
      env:
        HF_HUB_TOKEN: ${{ secrets.HF_HUB_TOKEN }}

    - name: Push model to Hugging Face Hub
      run: |
        python training/push_to_hub.py
