name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
 cd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download trained model artifact
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: ./my_sentiment_model

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Hugging Face Hub library
      run: pip install huggingface_hub

    - name: Login to Hugging Face Hub
      uses: huggingface/login@v0
      env:
        HF_HUB_TOKEN: ${{ secrets.HF_HUB_TOKEN }}

    - name: Push model to Hugging Face Hub
      run: |
        python training/push_to_hub.py
