name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Set PYTHONPATH for tests
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub
    
    - name: Download trained model artifact
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: ./my_sentiment_model

    - name: Run unit tests
      run: |
        pytest tests/

    - name: Train and evaluate model
      run: |
        python training/train.py


