name: Monitoring TweetEval

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # ogni giorno alle 2:00 UTC
  workflow_dispatch:     # per eseguire manualmente se vuoi

jobs:
  run-monitoring-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9 # problemi di compatibilità con ubuntu

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install datasets transformers torch matplotlib scikit-learn

    - name: Run monitoring test script
      run: python monitoring/monitoring.py